import "./globals.css";
import { Header, Sidebar } from "./ui";

export const metadata = {
  title: "AlJanat",
  description: "Generated by Mehran Ali",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <Sidebar />
          <div className="content">
            <Header />
            <div className="contentInner">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
