import "./globals.css";

export const metadata = {
  title: "AlJanat",
  description: "Generated by Mehran Ali",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
